# Generated by Django 3.0.3 on 2020-06-25 17:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('basic_portfolio_app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='About_certi',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('c_title', models.CharField(max_length=256)),
                ('c_date', models.DateField()),
                ('c_url', models.URLField()),
                ('c_number', models.CharField(max_length=256)),
                ('c_doc', models.FileField(upload_to='static/certificates')),
            ],
        ),
        migrations.CreateModel(
            name='About_framework',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('framework_name', models.CharField(max_length=256)),
                ('f_level', models.PositiveIntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='About_language',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('language_name', models.CharField(max_length=256)),
                ('l_level', models.PositiveIntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Experience',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=256)),
                ('job_profile', models.CharField(max_length=256)),
                ('description', models.CharField(max_length=500)),
                ('link', models.URLField()),
                ('tech_stack', models.CharField(max_length=256)),
                ('logo', models.ImageField(upload_to='static/experience_logo')),
            ],
        ),
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=256)),
                ('logo', models.ImageField(upload_to='static/project_logo')),
                ('github_link', models.URLField()),
                ('other_link', models.URLField()),
                ('description', models.CharField(max_length=500)),
                ('tech_stack', models.CharField(max_length=256)),
            ],
        ),
    ]
