# Generated by Django 3.0.3 on 2020-06-26 09:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('basic_portfolio_app', '0003_about_cv'),
    ]

    operations = [
        migrations.AlterField(
            model_name='about_cv',
            name='cv',
            field=models.FileField(upload_to='static/cv'),
        ),
    ]
