# Generated by Django 3.0.3 on 2020-07-21 13:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('basic_portfolio_app', '0004_auto_20200626_1514'),
    ]

    operations = [
        migrations.AddField(
            model_name='about_certi',
            name='c_company',
            field=models.CharField(default='NaN', max_length=256),
        ),
        migrations.AlterField(
            model_name='about_certi',
            name='c_doc',
            field=models.FileField(upload_to='certificates'),
        ),
        migrations.AlterField(
            model_name='about_cv',
            name='cv',
            field=models.FileField(upload_to='cv'),
        ),
        migrations.AlterField(
            model_name='experience',
            name='logo',
            field=models.ImageField(upload_to='experience_logo'),
        ),
        migrations.AlterField(
            model_name='homepage',
            name='fav_code',
            field=models.ImageField(upload_to='codesnippet'),
        ),
        migrations.AlterField(
            model_name='homepage',
            name='profile_pic',
            field=models.ImageField(upload_to='profilepic'),
        ),
        migrations.AlterField(
            model_name='project',
            name='logo',
            field=models.ImageField(upload_to='project_logo'),
        ),
    ]
